version: "3"

services:

  influxdb:
    build: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /var/lib/influxdb/:${PREFIX_DIR}/var/lib/influxdb/

  kapacitor:
    build: kapacitor
    volumes:
      - /var/log/kapacitor/:${PREFIX_DIR}/var/log/kapacitor/
    links:
      - influxdb

  chronograf:
    build: chronograf
    ports:
      - "8888:8888"
    volumes:
      - /var/lib/chronograf/:${PREFIX_DIR}/var/lib/chronograf/
    links:
      - influxdb

  nginx:
    build: nginx
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - ${PREFIX_DIR}/etc/nginx/ssl/:/etc/nginx/ssl/:ro
      - ${PREFIX_DIR}/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ${PREFIX_DIR}/var/log/nginx/:/var/log/nginx/
    links:
      - influxdb
